# Generated by Django 5.2.8 on 2026-02-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prolean', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLiveStudentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('agora_uid', models.CharField(db_index=True, max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('watch_seconds', models.PositiveIntegerField(default=0)),
                ('speaks', models.PositiveIntegerField(default=0)),
                ('hands', models.PositiveIntegerField(default=0)),
                ('engagement', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_live_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'user'], name='Prolean_ext_session_eb46ea_idx')],
                'unique_together': {('session_id', 'agora_uid')},
            },
        ),
    ]
