# Generated by Django 5.2.8 on 2026-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prolean', '0003_externallivesecurityevent_externallivesessionban'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallivestudentstat',
            name='hand_raised_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='externallivestudentstat',
            name='speaking_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
