# Generated by Django 5.2.8 on 2026-02-23 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prolean', '0004_externallivestudentstat_hand_raised_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLiveJoinInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('used_user_agent', models.TextField(blank=True, default='')),
                ('used_device_label', models.CharField(blank=True, default='', max_length=120)),
                ('used_sec_ch_ua', models.TextField(blank=True, default='')),
                ('used_sec_ch_platform', models.CharField(blank=True, default='', max_length=60)),
                ('used_sec_ch_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_live_join_invites_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_live_join_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'user', 'created_at'], name='Prolean_ext_session_ba0348_idx'), models.Index(fields=['session_id', 'user', 'used_at'], name='Prolean_ext_session_262f8f_idx')],
            },
        ),
    ]
