# Generated by Django 5.2.8 on 2026-02-23 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prolean', '0005_externallivejoininvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAuthorityUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(db_index=True, max_length=32)),
                ('external_user_id', models.CharField(db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_authority_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['authority', 'external_user_id'], name='Prolean_ext_authori_f8a139_idx'), models.Index(fields=['authority', 'user'], name='Prolean_ext_authori_9dec54_idx')],
                'unique_together': {('authority', 'external_user_id')},
            },
        ),
    ]
