# Generated by Django 5.2.8 on 2026-03-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prolean', '0008_external_live_join_invites_patch_all_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLiveRaiseHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('speaking', 'Speaking'), ('finished', 'Finished'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_live_raise_hands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raise_hands',
            },
        ),
        migrations.AddIndex(
            model_name='externalliveraisehand',
            index=models.Index(fields=['session_id', 'status', 'created_at'], name='raise_hands_session_4e80b8_idx'),
        ),
        migrations.AddIndex(
            model_name='externalliveraisehand',
            index=models.Index(fields=['session_id', 'student'], name='raise_hands_session_701b6b_idx'),
        ),
    ]
