# Generated by Django 5.2.8 on 2026-03-15 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prolean', '0009_externalliveraisehand_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externallivejoinattempt',
            new_name='Prolean_ext_session_9f904c_idx',
            old_name='Prolean_attempt_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='externallivejoinattempt',
            new_name='Prolean_ext_ip_addr_fe9a87_idx',
            old_name='Prolean_attempt_ip_created_idx',
        ),
        migrations.RenameIndex(
            model_name='externallivejoinattempt',
            new_name='Prolean_ext_token_h_43b693_idx',
            old_name='Prolean_attempt_token_created_idx',
        ),
        migrations.RenameIndex(
            model_name='externallivejoinattempt',
            new_name='Prolean_ext_status_e9eae2_idx',
            old_name='Prolean_attempt_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='externallivejoininvite',
            new_name='Prolean_ext_session_c3afd5_idx',
            old_name='Prolean_ext_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='externallivejoininvite',
            new_name='Prolean_ext_session_2ccb4c_idx',
            old_name='Prolean_ext_session_cin_idx',
        ),
        migrations.RenameIndex(
            model_name='externallivejoininvite',
            new_name='Prolean_ext_session_d0344d_idx',
            old_name='Prolean_ext_session_used_idx',
        ),
        migrations.AddField(
            model_name='externalliveraisehand',
            name='end_speaking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalliveraisehand',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalliveraisehand',
            name='network_quality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='externalliveraisehand',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='externalliveraisehand',
            name='start_speaking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalliveraisehand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('speaking', 'Speaking'), ('finished', 'Finished'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], db_index=True, default='pending', max_length=16),
        ),
    ]
