"""
Django settings for Project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env() -> None:
    env_file = BASE_DIR / '.env'
    if not env_file.exists():
        return
    for line in env_file.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9^0!3pixm64jjc(h$wyprge$25ryvj+ld8mze*$dp@d+ck5_9i'

# SECURITY WARNING: don't run with debug turned on in production!
def _env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)).strip())
    except (TypeError, ValueError):
        return default


def _env_csv(name: str) -> list[str]:
    raw = os.getenv(name, "").strip()
    if not raw:
        return []
    return [v.strip() for v in raw.split(",") if v.strip()]


DEBUG = _env_bool("DEBUG", False)

ALLOWED_HOSTS = _env_csv("ALLOWED_HOSTS") or ["*"]

# Railway (and most PaaS) runs Django behind a proxy/ingress; ensure HTTPS is
# correctly detected for security features like CSRF Origin checking.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF origin allowlist must include scheme (https://...). Configure via env
# for custom domains; default covers Railway app domains.
_default_csrf_trusted_origins = [
    # Railway default domains
    "https://*.up.railway.app",
    "https://proleanproject-production.up.railway.app",
    # Some proxy setups may forward http internally; keep this to avoid false positives.
    "http://proleanproject-production.up.railway.app",
]
CSRF_TRUSTED_ORIGINS = sorted(set(_default_csrf_trusted_origins + _env_csv("CSRF_TRUSTED_ORIGINS")))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Prolean',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'Prolean.middleware.AutoLanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'Prolean.middleware.ExternalAuthorityGuardMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Add your custom context processors
                'Prolean.context_processors.currency_rates',
                'Prolean.context_processors.user_location',
                'Prolean.context_processors.site_settings',
                'Prolean.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
def _env_db_url(name: str) -> str:
    raw = os.getenv(name)
    if raw is None:
        return ""
    raw = str(raw).strip()
    if not raw or raw.lower() in {"none", "null", "unset", "false", "0"}:
        return ""
    return raw


database_url = _env_db_url('DATABASE_PUBLIC_URL') or _env_db_url('DATABASE_URL')

if database_url:
    parsed_db = urlparse(database_url)
    db_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed_db.path.lstrip('/'),
        'USER': parsed_db.username,
        'PASSWORD': parsed_db.password,
        'HOST': parsed_db.hostname,
        'PORT': str(parsed_db.port or 5432),
    }
    if parsed_db.hostname and not parsed_db.hostname.endswith('railway.internal'):
        db_config['OPTIONS'] = {'sslmode': 'require'}
    DATABASES = {'default': db_config}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Casablanca'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = _env_int('SESSION_COOKIE_AGE', 1209600)  # 2 weeks
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')

# Security settings for rate limiting
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Rate limiting
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'Prolean.views.rate_limit_exceeded'
# Cache Configuration (Using Django's built-in cache for now)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'
LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
    ('ar', _('Arabic')),
]

# Messages
# Use cookie storage so UI feedback does not depend on DB-backed sessions.
MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"
LOCALE_PATHS = [BASE_DIR / 'locale']

# Logging
# Ensure 500 tracebacks are visible in Railway/Gunicorn logs.
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").strip().upper() or "INFO"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "Prolean": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_TZ = True

# Presence/Geo tuning
PROLEAN_PRESENCE_TTL_SECONDS = _env_int("PROLEAN_PRESENCE_TTL_SECONDS", 120)
PROLEAN_PRESENCE_INDEX_LIMIT = _env_int("PROLEAN_PRESENCE_INDEX_LIMIT", 3000)
PROLEAN_GEOIP_CACHE_SECONDS = _env_int("PROLEAN_GEOIP_CACHE_SECONDS", 21600)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration
# For development: use console backend
# For production: configure SMTP settings below

# Development (console)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production (SMTP) - Uncomment and configure
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your SMTP provider (smtp.sendgrid.net, email-smtp.eu-west-1.amazonaws.com, etc.)
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'your-app-password'  # Replace with your app password
DEFAULT_FROM_EMAIL = 'Prolean Centre <noreply@prolean.com>'
SERVER_EMAIL = 'admin@prolean.com'

# Email Templates
EMAIL_SUBJECT_PREFIX = '[Prolean] '

# Auth Redirects
LOGIN_REDIRECT_URL = 'Prolean:dashboard'
LOGOUT_REDIRECT_URL = 'home'
# Use the namespaced Prolean login route so login_required redirects correctly.
# (Using a bare string like "login" can become a relative URL depending on resolver context.)
LOGIN_URL = 'Prolean:login'

# External contract settings (management system as source of truth)
PROLEAN_MANAGEMENT_API_BASE_URL = os.getenv('PROLEAN_MANAGEMENT_API_BASE_URL', '')
PROLEAN_MANAGEMENT_API_TOKEN = os.getenv('PROLEAN_MANAGEMENT_API_TOKEN', '')
PROLEAN_MANAGEMENT_SERVICE_USERNAME = os.getenv('PROLEAN_MANAGEMENT_SERVICE_USERNAME', '')
PROLEAN_MANAGEMENT_SERVICE_PASSWORD = os.getenv('PROLEAN_MANAGEMENT_SERVICE_PASSWORD', '')
PROLEAN_MANAGEMENT_API_TIMEOUT_SECONDS = int(os.getenv('PROLEAN_MANAGEMENT_API_TIMEOUT_SECONDS', '8'))
PROLEAN_MANAGEMENT_API_MAX_RETRIES = int(os.getenv('PROLEAN_MANAGEMENT_API_MAX_RETRIES', '2'))
PROLEAN_EXTERNAL_ACCESS_CACHE_TTL_SECONDS = int(os.getenv('PROLEAN_EXTERNAL_ACCESS_CACHE_TTL_SECONDS', '60'))
PROLEAN_EXTERNAL_HEALTH_CACHE_TTL_SECONDS = int(os.getenv('PROLEAN_EXTERNAL_HEALTH_CACHE_TTL_SECONDS', '30'))
PROLEAN_STRICT_AUTHORITY_MODE = os.getenv('PROLEAN_STRICT_AUTHORITY_MODE', 'false').lower() == 'true'
PROLEAN_READ_ONLY_ON_OUTAGE = os.getenv('PROLEAN_READ_ONLY_ON_OUTAGE', 'true').lower() == 'true'

# Agora (live streaming provider)
# Support multiple env key variants to avoid deployment misconfiguration.
AGORA_APP_ID = (
    os.getenv('AGORA_APP_ID')
    or os.getenv('AGORA_APPID')
    or os.getenv('APP_ID')
    or ''
)
AGORA_APP_CERTIFICATE = (
    os.getenv('AGORA_APP_CERTIFICATE')
    or os.getenv('AGORA_PRIMARY_CERTIFICATE')
    or os.getenv('AGORA_CERTIFICATE')
    or os.getenv('PRIMARY_CERTIFICATE')
    or ''
)
AGORA_TOKEN_EXPIRY_SECONDS = int(os.getenv('AGORA_TOKEN_EXPIRY_SECONDS', '3600'))
